# Generated by Django 4.2 on 2023-10-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naivebaker_app', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_time',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
