# Generated by Django 4.2.6 on 2023-11-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naivebaker_app', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mealtimes',
            field=models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER')], default='breakfast', max_length=40),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealtypes',
            field=models.CharField(choices=[('indian', 'INDIAN'), ('thai', 'THAI'), ('mexican', 'MEXICAN'), ('french', 'FRENCH'), ('chinese', 'CHINESE')], default='indian', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='types',
            field=models.CharField(choices=[('veg', 'VEG'), ('nonveg', 'NONVEG')], default='veg', max_length=10),
        ),
    ]
