# Generated by Django 4.2.6 on 2023-11-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naivebaker_app', '0008_alter_recipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='owner',
        ),
    ]
