# Generated by Django 4.2.6 on 2023-11-03 14:30

from django.db import migrations, models
import naivebaker_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('naivebaker_app', '0009_rename_user_recipe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=naivebaker_app.models.filepath),
        ),
    ]
