# Generated by Django 4.2.6 on 2023-11-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naivebaker_app', '0010_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mealtypes',
            field=models.CharField(choices=[('indian', 'INDIAN'), ('thai', 'THAI'), ('mexican', 'MEXICAN'), ('french', 'FRENCH'), ('chinese', 'CHINESE')], max_length=20),
        ),
    ]
