# Generated by Django 4.2.6 on 2023-11-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naivebaker_app', '0011_alter_recipe_mealtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vegitarity',
            field=models.CharField(default='veg', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mealtypes',
            field=models.CharField(choices=[('indian', 'INDIAN'), ('thai', 'THAI'), ('mexican', 'MEXICAN'), ('french', 'FRENCH'), ('chinese', 'CHINESE')], default='indian', max_length=20),
        ),
    ]
