# Generated by Django 4.2.6 on 2023-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naivebaker_app', '0012_recipe_vegitarity_alter_recipe_mealtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='Indian', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_time',
            field=models.CharField(default='breakfast', max_length=20, null=True),
        ),
    ]
