# Generated by Django 4.2.6 on 2023-11-09 09:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('naivebaker_app', '0014_saved_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='saved_recipe',
            new_name='save_recipe',
        ),
    ]
