# Generated by Django 4.2.6 on 2023-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naivebaker_app', '0016_rename_category_save_recipe_cusinetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save_recipe',
            old_name='name',
            new_name='recipename',
        ),
        migrations.AddField(
            model_name='save_recipe',
            name='cooklink',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='save_recipe',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
