# Generated by Django 4.2.6 on 2023-11-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naivebaker_app', '0017_rename_name_save_recipe_recipename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_recipe',
            name='image',
            field=models.TextField(default='', max_length=15),
        ),
    ]
